### ISSUE TITLE
Img Link Broken

### ISSUE THREAD

**Issue by CodyBakerOnshore** [atillabyte/FFMinimalDark#1]
Hi,
Just to let you know the link to your image for the style seems to be broken? appears to be sending me to this url: https://camo.githubusercontent.com/5c1cf7dc6879ac07bc862c3de616b88f00540e80/68747470733a2f2f6174696c2e6c612f782f696d672f786d4c6272486a57695a2e706e67, I am receiving a 404 error on a blank page when I go to that url, If that is any help at all. Perhaps check if whatever host the image was on has deleted it at some point?

**Comment by atillabyte** [comment]
Unfortunately, it appears that GitHub doesn't allow direct hot linking to repository assets anymore. I'm archiving this repository now anyhow considering that there's a native dark theme with a significant amount of slimming in FF Quantum. Thank you for the issue nonetheless!
